### ISSUE TITLE
Add config option to disable highlighting chunkloaders

### ISSUE THREAD

**Issue by redxtech** [WobbyChip/Minecraft-Plugins#1]
When the chunkloaders are active, they are of course highlighted green. This isn't working out so well on my SMP server I'm running with some friends, because there are a lot of people on the server, and they don't know what it is, so they'll mine it out of curiosity, and break it.

I think it would be great if you could add a config option to disable the highlighting of the chunkloader through other blocks, that way people won't assume it's something they should go and break.

Thanks!

**Comment by WobbyChip** [comment]
Added option to disable highlighting to config.
To use it you will have to delete the old config file.

**Comment by redxtech** [comment]
What a nice fix, I love how efficient this change is!

Is there a prebuilt binary available yet or should I try and build from source to start using this?

**Comment by redxtech** [comment]
Nvm, I just downloaded the jar file from the repo.

It works perfectly, thank you!
