### ISSUE TITLE
Arrow of Explosion Don't Actually Explode

### ISSUE THREAD

**Issue by valous2** [WobbyChip/Minecraft-Plugins#3]
I crafted a few stacks of arrows of explosions and they make the sound of an explosion on impact but there is no actual terrain damage. Was wanting to use them as a fun alternative for blast mining on my server. The splash potions work as intended but since they are not stackable one is better off just using regular tnt for this purpose.

**Comment by WobbyChip** [comment]
This is intended. Don't you think that making 8 arrows from one potion and using them as the same would be balanced?

**Comment by valous2** [comment]
While I do agree that the arrows being as strong as the potions would be unbalanced, they should do some damage to the area, even if it just a few blocks as most arrows in the game function like the potions just on a weaker scale. As it stands It is not clear what these arrows do as there no documentation on them in the game or online that I can find.
