### ISSUE TITLE
1.20.2 not working

### ISSUE THREAD

**Issue by LisicaQ** [WobbyChip/Minecraft-Plugins#5]
I downloaded a1.20.2 spigot server and only have the smptweaks plugin in as of now and i get this error. 

![image](https://github.com/WobbyChip/Minecraft-Plugins/assets/68858207/89d41b9d-df40-4a6b-ad56-76b685d2cc07)

**Comment by WobbyChip** [comment]
Did you download from here: https://github.com/WobbyChip/Minecraft-Plugins/releases/tag/smptweaks-v1.20.2

**Comment by WobbyChip** [comment]
Use this one for now, new one has something broken with config extraction.
[SMPTweaks.zip](https://github.com/WobbyChip/Minecraft-Plugins/files/13404555/SMPTweaks.zip)
